### ISSUE TITLE
Cant disable cover system

### ISSUE THREAD

**Issue by thecuban** [shaygman/MCC_sandbox_modDev#14]
I'm having an issue disabling the cover system, in that I cant. when I open mcc the option to toggle it on and off seems to be disabled and cant be clicked. the only workaround I have found so far is to log in and manually disable it in the mission settings for each mission, but that gets tiresome when it needs to be done for every mission

**Comment by thecuban** [comment]
In fact its grayed out and disabled in the same way that the controls options are when using CBA

**Comment by shaygman** [comment]
Closed - duplicated - https://github.com/shaygman/MCC_sandbox_modDev/issues/12
