### ISSUE TITLE
ACE Medical (AI Unconsciousness) / ACE Revive (AI in revive state)

### ISSUE THREAD

**Issue by m240** [shaygman/MCC_sandbox_modDev#39]
MCC is not counting kills at all when using ACE Revive system and is counting only about half of them (probably just the instant kills - like the ones from explosions or headshots) when using AI Unconsciousness within ACE Medical system, thus not allowing players to properly exp from killing enemy, so it really makes those functions incompatible with Role Selection.
We would appreciate if you could add a new function or script that would be checking if ACE AI unconsciousness is enabled within ACE Medical and then check if unit is "ACE_isUnconscious = true" or if the ACE Revive is enabled and then check for the "inReviveState = true".
I'm not 100% sure those are correct functions because I'm just a dummy when it comes to "that stuff" so please check if those are the ones you should use. 
I think putting your enemy into revive state could be counted as legit kill because they will 100% die if they would not be treated by medic and there's no chance they will "wake up" on their own, but a unit can sometimes wake up from unconsciousness (without any external help) a few times before dying so beware that this could lead to a weird situation when you would get in example 2-3 kills for hitting the same AI or player unit. 
So maybe the solution would be iincorporating functions from "acex_killtracker" in that situation because it's counting the "kill" only if the unit really died. 
I've found this when I tried to search about the solution so maybe it would help you in this particular issue https://github.com/acemod/ACE3/issues/4993#issuecomment-286761858 
From what've I tested that acex_killtracker thing is working reliably to count kills, tested just with "briefing output":

class CfgDebriefingSections 
{
        class acex_killTracker 
		{
            title = "Acex Killed Events";
            variable = "acex_killTracker_outputText";
        };
};

in the description.ext of my mission.

Maybe there's just a thing that I need to put into my mission init/description using already existing function from ACEX, but forgive me, like I've said I just don't have enough skills to figure this out. 
Thanks for a great mod and in advance for any help on that issue!

**Comment by m240** [comment]
It seems like you figured it out before I've send the ticket. Actually yours wasn't there when I started but I've had to go out and when I came back I've just finished and sent it without noticing that issues were updated already, so sorry for inconvenience ;)

**Comment by shaygman** [comment]
Thanks to your help I was able to fix it and will be released in next version AKA r25
