### ISSUE TITLE
Unable to perform medical actions on self using MCC self interaction

### ISSUE THREAD

**Issue by BigDrewy1** [shaygman/MCC_sandbox_modDev#52]
Environment: SP

Mods used: MCCS4, CBAA3, Change weapons while moving, mao sway fix, splendid smoke, project infinite - inspect weapons, unit voiceovers, rhs replacement pack, nato replacement hq, nato replacement uniform pack, nato_rus_vehicle, nato_rus_weapons, Ni arms all in one, RH acc 1.06, rh pistol pack, rh m4, rhsusaf, ussocom_mas, ussocom_vehicles_mas, vsm all in one collection

**THE ISSUE IS HOWEVER PRESENT WHEN THE ONLY MOD LOADED AT GAME START IS MCCS4**

Mission template: Stock BIS The East Wind Campaign

Experiencing an issue where using the self interaction menu to use the medical system, only a tiny fraction of a healing operation happens before the operation is abandoned. Cannot heal myself, only squadmates.

Operation begins, ~10% of the bar fills, operation aborts, used medical textures appear beside the player, and no change is enacted.
Whether using bandages, MedKit, FAIK, saline, whatever, it always happens

To reproduce the error:
Start ARMA3 with MCCS4 the solely activated mod
Load any BIS main campaign mission
Open MCC
Navigate to mission settings, enable self interaction and the self interaction UI
Navigate to medical system, enable, bug present on complex and simple, (only medic can heal - disabled)
Self interact to use the medical system - any operation selected is immediately aborted without any affect, used medical supplies does however appear on the ground.
AM ABLE TO *TREAT SELF* WITH A YELLOW FAIK USING THE BIS INTERACTION MENU

I have also noticed that if I turn on interaction without enabling the medical system, I still have access to medical functions when interacting with AI. To see the medical functions on self interact, the medical system must be enabled.

**Comment by shaygman** [comment]
Fixed
