### ISSUE TITLE
(MCC) Ammo box falls through terrain with ACE

### ISSUE THREAD

**Issue by CplCandyBar** [shaygman/MCC_sandbox_modDev#56]
MCC_ammoBoxMag appears to deploy at too low a height, making it fall through level terrain or positive inclines. Suggest somehow raising the height at which it deploys?

Steps to reproduce:
-Load MCC, CBA and ACE 3
-Acquire an ammo box
-Attempt to deploy it on perfectly flat ground or a positive incline
-Observe your hopes and dreams slipping through your ammo-starved fingers

**Comment by shaygman** [comment]
Fixed will be available in R26
